import type { Metadata } from "next";

import "./globals.css";
import Providers from "./providers";
import Image from "next/image";
import NegotiateSVG from "../../negotiate.svg";
import Link from "next/link";
import { Header } from "@/components/Header";
import { Toaster } from "sonner";
import { Separator } from "@/components/ui/separator";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-[1050px] mx-auto">
        <Providers>
          <Header />
          <div>
            <Link href="/">
              <Image
                src={NegotiateSVG}
                alt="logo"
                className="mx-auto cursor-pointer"
              />
            </Link>
            <h1 className="font-['Agdasima'] text-3xl text-center">
              StealthBid
            </h1>
            {children}
          </div>
          <footer>
            <Separator
              orientation="vertical"
              className="h-[1px] bg-[#000] w-100 my-2"
            />
            <p className="text-center text-gray-500">
              Built with ❤️ by Ivan Asenov &{" "}
              <a
                href="https://www.linkedin.com/in/ivaylo-nikolov-dev/"
                className="text-primary"
              >
                Ivaylo Nikolov
              </a>
            </p>
          </footer>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
